import { BaseMarkdownParser } from './BaseMarkdownParser';
import { ChatData, ChatMessage, ChatMessageType, ChatMetadata } from '../../../types';

/**
 * GeminiNotebookMarkdownParser specifically handles the Gemini Notebook
 * exports generated by the platform's DOM scrapers.
 */
export class GeminiNotebookMarkdownParser extends BaseMarkdownParser {
    parse(input: string): ChatData {
        const metadata = this.extractGeminiNotebookMetadata(input);
        const messages = this.parseGeminiNotebookTurns(input);

        if (messages.length === 0) {
            // Fallback to standard turns if specialized fails
            const fallbackMessages = this.parseStandardTurns(input);
            if (fallbackMessages.length === 0) {
                throw new Error('No valid Gemini Notebook conversation turns detected. Ensure "#### Prompt - User" headings are present.');
            }
            return { messages: fallbackMessages, metadata };
        }

        return { messages, metadata };
    }

    private extractGeminiNotebookMetadata(input: string): ChatMetadata {
        const metadata: ChatMetadata = {
            title: 'Gemini Notebook Conversation',
            model: 'Gemini Notebook',
            date: new Date().toISOString(),
            tags: ['gemini-notebook']
        };

        // 1. Title detection from H1 header
        const h1Match = input.match(/^#\s+(.+)/m);
        if (h1Match) {
            metadata.title = h1Match[1].trim();
        }

        // 2. Extract Date
        const dateMatch = input.match(/>\s*\*\*🌐 Date:\*\*\s*(.+)/i);
        if (dateMatch) {
            metadata.date = dateMatch[1].trim();
        }

        // 3. Extract Source
        const sourceMatch = input.match(/>\s*\*\*🌐 Source:\*\*\s*\[.+\]\((.+)\)/i);
        if (sourceMatch) {
            metadata.sourceUrl = sourceMatch[1].trim();
        }

        // 4. Extract Tags
        const tagsMatch = input.match(/>\s*\*\*🏷️ Tags:\*\*\s*(.+)/i);
        if (tagsMatch) {
            const tags = tagsMatch[1].split(',').map(t => t.trim().toLowerCase());
            metadata.tags = Array.from(new Set([...metadata.tags, ...tags]));
        }

        return metadata;
    }

    private parseGeminiNotebookTurns(input: string): ChatMessage[] {
        const messages: ChatMessage[] = [];

        // Match either Prompt - User or Response - NotebookLM headers (case-insensitive, optional emojis)
        const headerPattern = /^(?:###|####)\s+(Prompt\s*-\s*User|Response\s*-\s*NotebookLM)(?:\s+-\s+[^:\n]+)?(?:\s+[👤🤖])?:/gimu;

        const matches = Array.from(input.matchAll(headerPattern));
        if (matches.length === 0) return [];

        for (let i = 0; i < matches.length; i++) {
            const headerType = matches[i][1].toLowerCase();
            const contentStart = matches[i].index! + matches[i][0].length;
            const contentEnd = (i + 1 < matches.length)
                ? matches[i + 1].index
                : input.search(/\n---\n\n###### Noosphere Reflect/);

            let rawContent = input.substring(contentStart, contentEnd === -1 ? input.length : contentEnd).trim();

            // Detect thoughts if any (standard format)
            let thoughts: string | undefined;
            const thoughtMatch = rawContent.match(/```\nThoughts:\n([\s\S]*?)```/im) ||
                rawContent.match(/```thought\n([\s\S]*?)```/im) ||
                rawContent.match(/<thoughts>([\s\S]*?)<\/thoughts>/im);

            if (thoughtMatch) {
                thoughts = thoughtMatch[1].trim();
                rawContent = rawContent.replace(thoughtMatch[0], '').trim();
            }

            const isPrompt = headerType.includes('prompt');

            let finalContent = rawContent;
            if (!isPrompt && thoughts) {
                finalContent = `<thoughts>\n\n${thoughts}\n\n</thoughts>\n\n${rawContent}`;
            }

            messages.push({
                type: isPrompt ? ChatMessageType.Prompt : ChatMessageType.Response,
                content: finalContent
            });
        }

        return messages;
    }
}
